# CREATING LABELS

Creating the labels for traffic using equal weightage for the weights of the 3 terms in the equation. This converts the unsupervised problem into a supervised problem. Equation:

#### Traffic = A·max((weekend || holiday), 0.05 ) + B·max(peak_hr,0.1) + C·max(hotspot, 0.1)+ ɛ

In [1]:
import pandas as pd
import sys

In [3]:
#Loading the checkpoint5 
checkpoint5 = pd.read_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/checkpoint-5.csv')
checkpoint5.head(5)

,fare_amount,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,time,day,weekend,holiday,peak_hour,hotspot,dist
0,4.5,-73.844311,40.721319,-73.841610,40.712278,1,17:26:21,0,False,0,1,0,1.030764
1,16.9,-74.016048,40.711303,-73.979268,40.782004,1,16:52:16,1,False,0,1,0,8.450134
2,5.7,-73.982738,40.761270,-73.991242,40.750562,2,00:35:00,3,False,0,0,1,1.389525
3,7.7,-73.987130,40.733143,-73.991567,40.758092,1,04:30:42,5,True,0,0,1,2.799270
4,5.3,-73.968095,40.768008,-73.956655,40.783762,1,07:51:00,1,False,0,1,0,1.999157

In [2]:
kaggle_test = pd.read_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/processed_kaggle_test.csv')
kaggle_test.head(5)

,key,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,time,day,weekend,holiday,peak_hour,hotspot,dist
0,2015-01-27 13:08:24.0000002,-73.973320,40.763805,-73.981430,40.743835,1,13:08:24,1,False,0,0,0,2.323260
1,2015-01-27 13:08:24.0000003,-73.986862,40.719383,-73.998886,40.739201,1,13:08:24,1,False,0,0,0,2.425353
2,2011-10-08 11:53:44.0000002,-73.982524,40.751260,-73.979654,40.746139,1,11:53:44,5,True,0,0,0,0.618628
3,2012-12-01 21:12:12.0000002,-73.981160,40.767807,-73.990448,40.751635,1,21:12:12,5,True,0,0,0,1.961033
4,2012-12-01 21:12:12.0000003,-73.966046,40.789775,-73.988565,40.744427,1,21:12:12,5,True,0,0,1,5.387301

In [4]:
labels = checkpoint5[['fare_amount']]
labels

          fare_amount
0                 4.5
1                16.9
2                 5.7
3                 7.7
4                 5.3
...               ...
54125939         14.0
54125940          4.2
54125941         14.1
54125942         28.9
54125943          7.5

[54125944 rows x 1 columns]

In [5]:
del checkpoint5['fare_amount']
checkpoint5

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,time,day,weekend,holiday,peak_hour,hotspot,dist
0,-73.844311,40.721319,-73.841610,40.712278,1,17:26:21,0,False,0,1,0,1.030764
1,-74.016048,40.711303,-73.979268,40.782004,1,16:52:16,1,False,0,1,0,8.450134
2,-73.982738,40.761270,-73.991242,40.750562,2,00:35:00,3,False,0,0,1,1.389525
3,-73.987130,40.733143,-73.991567,40.758092,1,04:30:42,5,True,0,0,1,2.799270
4,-73.968095,40.768008,-73.956655,40.783762,1,07:51:00,1,False,0,1,0,1.999157
...,...,...,...,...,...,...,...,...,...,...,...,...
54125939,-74.005272,40.740027,-73.963280,40.762555,1,03:28:00,5,True,0,0,0,4.334397
54125940,-73.957784,40.765530,-73.951640,40.773959,1,20:46:20,1,False,0,0,0,1.070590
54125941,-73.970505,40.752325,-73.960537,40.797342,1,22:04:24,5,True,0,0,0,5.075548
54125942,-73.980901,40.764629,-73.870605,40.773963,1,05:57:51,2,False,0,0,0,9.346157
54125943,-73.969722,40.797668,-73.970885,40.783313,1,11:33:00,4,True,0,0,0,1.599203

In [3]:
del kaggle_test['time']
kaggle_test

,key,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,day,weekend,holiday,peak_hour,hotspot,dist
0,2015-01-27 13:08:24.0000002,-73.973320,40.763805,-73.981430,40.743835,1,1,False,0,0,0,2.323260
1,2015-01-27 13:08:24.0000003,-73.986862,40.719383,-73.998886,40.739201,1,1,False,0,0,0,2.425353
2,2011-10-08 11:53:44.0000002,-73.982524,40.751260,-73.979654,40.746139,1,5,True,0,0,0,0.618628
3,2012-12-01 21:12:12.0000002,-73.981160,40.767807,-73.990448,40.751635,1,5,True,0,0,0,1.961033
4,2012-12-01 21:12:12.0000003,-73.966046,40.789775,-73.988565,40.744427,1,5,True,0,0,1,5.387301
...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,-73.968124,40.796997,-73.955643,40.780388,6,6,True,0,0,0,2.124874
9910,2015-01-12 17:05:51.0000001,-73.945511,40.803600,-73.960213,40.776371,6,0,False,0,1,0,3.270969
9911,2015-04-19 20:44:15.0000001,-73.991600,40.726608,-73.789742,40.647011,6,6,True,0,0,0,19.183941
9912,2015-01-31 01:05:19.0000005,-73.985573,40.735432,-73.939178,40.801731,6,5,True,0,0,0,8.343486
9913,2015-01-18 14:06:23.0000006,-73.988022,40.754070,-74.000282,40.759220,6,6,True,0,0,1,1.180825

In [6]:
#Getting the summary of the dataset
shape = checkpoint5.shape

NUM_ROWS = shape[0]
NUM_COLS = shape[1]

print("Number of Rows:", NUM_ROWS)
print("NUmber of Columns:", NUM_COLS)

Number of Rows: 54125944
NUmber of Columns: 12

In [4]:
#Getting the summary of the dataset
shape = kaggle_test.shape

NUM_ROWS_TEST = shape[0]
NUM_COLS_TEST = shape[1]

print("Number of Rows:", NUM_ROWS_TEST)
print("NUmber of Columns:", NUM_COLS_TEST)

Number of Rows: 9914
NUmber of Columns: 12

In [7]:
#converting the weekend column from boolean to binary
checkpoint5.replace({False: 0, True: 1}, inplace=True)
checkpoint5

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,time,day,weekend,holiday,peak_hour,hotspot,dist
0,-73.844311,40.721319,-73.841610,40.712278,1,17:26:21,0,0,0,1,0,1.030764
1,-74.016048,40.711303,-73.979268,40.782004,1,16:52:16,1,0,0,1,0,8.450134
2,-73.982738,40.761270,-73.991242,40.750562,2,00:35:00,3,0,0,0,1,1.389525
3,-73.987130,40.733143,-73.991567,40.758092,1,04:30:42,5,1,0,0,1,2.799270
4,-73.968095,40.768008,-73.956655,40.783762,1,07:51:00,1,0,0,1,0,1.999157
...,...,...,...,...,...,...,...,...,...,...,...,...
54125939,-74.005272,40.740027,-73.963280,40.762555,1,03:28:00,5,1,0,0,0,4.334397
54125940,-73.957784,40.765530,-73.951640,40.773959,1,20:46:20,1,0,0,0,0,1.070590
54125941,-73.970505,40.752325,-73.960537,40.797342,1,22:04:24,5,1,0,0,0,5.075548
54125942,-73.980901,40.764629,-73.870605,40.773963,1,05:57:51,2,0,0,0,0,9.346157
54125943,-73.969722,40.797668,-73.970885,40.783313,1,11:33:00,4,1,0,0,0,1.599203

In [5]:
#converting the weekend column from boolean to binary
kaggle_test.replace({False: 0, True: 1}, inplace=True)
kaggle_test

,key,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,day,weekend,holiday,peak_hour,hotspot,dist
0,2015-01-27 13:08:24.0000002,-73.973320,40.763805,-73.981430,40.743835,1,1,0,0,0,0,2.323260
1,2015-01-27 13:08:24.0000003,-73.986862,40.719383,-73.998886,40.739201,1,1,0,0,0,0,2.425353
2,2011-10-08 11:53:44.0000002,-73.982524,40.751260,-73.979654,40.746139,1,5,1,0,0,0,0.618628
3,2012-12-01 21:12:12.0000002,-73.981160,40.767807,-73.990448,40.751635,1,5,1,0,0,0,1.961033
4,2012-12-01 21:12:12.0000003,-73.966046,40.789775,-73.988565,40.744427,1,5,1,0,0,1,5.387301
...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,-73.968124,40.796997,-73.955643,40.780388,6,6,1,0,0,0,2.124874
9910,2015-01-12 17:05:51.0000001,-73.945511,40.803600,-73.960213,40.776371,6,0,0,0,1,0,3.270969
9911,2015-04-19 20:44:15.0000001,-73.991600,40.726608,-73.789742,40.647011,6,6,1,0,0,0,19.183941
9912,2015-01-31 01:05:19.0000005,-73.985573,40.735432,-73.939178,40.801731,6,5,1,0,0,0,8.343486
9913,2015-01-18 14:06:23.0000006,-73.988022,40.754070,-74.000282,40.759220,6,6,1,0,0,1,1.180825

In [6]:
#function to calculate the equation
def calc_traffic_density(weekend, public_hol, peak_hr, hotspot):
    #defining the weights and the small constant
    WEIGHT_A = WEIGHT_B = WEIGHT_C = 1/3
    EPSILON = sys.float_info.epsilon
    
    #Getting the Unweighted values
    day = max((weekend or public_hol),0.05)
    time = max(peak_hr,0.1)
    place = max(hotspot,0.1)
    
    #Getting the Weighted Values
    weighted_day = WEIGHT_A * day
    weighted_time = WEIGHT_B * time
    weighted_place = WEIGHT_C * place
    
    #Summing up all the variables
    traffic = weighted_day + weighted_place + weighted_time + EPSILON
    
    return traffic

In [8]:
#Iterating through the dataset
traffic_density = []
for index, row in checkpoint5.iterrows():
    traffic_value = calc_traffic_density(weekend=row['weekend'], public_hol=row['holiday'], peak_hr=row['peak_hour'], hotspot=row['hotspot'])
    traffic_density.insert(index,traffic_value)

In [9]:
#Iterating through the dataset - kaggle test
traffic_density_kt = []
for index, row in kaggle_test.iterrows():
    traffic_value_kt = calc_traffic_density(weekend=row['weekend'], public_hol=row['holiday'], peak_hr=row['peak_hour'], hotspot=row['hotspot'])
    traffic_density_kt.insert(index,traffic_value_kt)

In [9]:
traffic_density

[0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.6833333333333336,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.6833333333333336,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 1.0000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.7000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 1.0000000000000002,
 0.08333333333333356,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 1.0000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 1.0000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 1.0000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 1.0000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 1.0000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 1.0000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.6833333333333336,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.6833333333333336,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 1.0000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 1.0000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 1.0000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.6833333333333336,
 0.7000000000000002,
 0.08333333333333356,
 0.6833333333333336,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 1.0000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.6833333333333336,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 1.0000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 1.0000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.7000000000000002,
 0.6833333333333336,
 0.7000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.6833333333333336,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.6833333333333336,
 1.0000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.6833333333333336,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 1.0000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.6833333333333336,
 0.6833333333333336,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.7000000000000002,
 0.6833333333333336,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.6833333333333336,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.6833333333333336,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.6833333333333336,
 0.7000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.6833333333333336,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.6833333333333336,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.6833333333333336,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.6833333333333336,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.6833333333333336,
 0.7000000000000002,
 0.6833333333333336,
 0.3833333333333335,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.6833333333333336,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.4000000000000002,
 1.0000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,

In [10]:
traffic_density_kt

[0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.7000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.7000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.4000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.7000000000000002,
 0.08333333333333356,
 0.3833333333333335,
 0.6833333333333336,
 0.08333333333333356,
 0.08333333333333356,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.7000000000000002,
 0.08333333333333356,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.3833333333333335,
 0.3833333333333335,
 0.3833333333333335,
 0.6833333333333336,
 0.4000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 1.0000000000000002,
 0.7000000000000002,
 0.7000000000000002,
 0.4000000000000002,
 0.4000000000000002,
 0.3833333333333335,
 0.08333333333333356,
 0.08333333333333356,
 0.08333333333333356,

In [10]:
#saving traffic_density
traffic_density_df = pd.DataFrame(traffic_density)
traffic_density_df.to_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/own_eqn/traffic_density_labels.csv', index=False)

In [12]:
#saving traffic_density kt
traffic_density_kt_df = pd.DataFrame(traffic_density_kt)
traffic_density_kt_df.to_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/own_eqn/kaggle_test_traffic_labels.csv', index=False)

In [8]:
#loading traffic density
traffic_density_df = pd.read_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/own_eqn/traffic_density_labels.csv')
traffic_density_df

                 0
0         0.383333
1         0.383333
2         0.383333
3         0.700000
4         0.383333
...            ...
54125939  0.400000
54125940  0.083333
54125941  0.400000
54125942  0.083333
54125943  0.400000

[54125944 rows x 1 columns]

In [13]:
#loading traffic density kt
traffic_density_kt_df = pd.read_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/own_eqn/kaggle_test_traffic_labels.csv')
traffic_density_kt_df

             0
0     0.083333
1     0.083333
2     0.400000
3     0.400000
4     0.700000
...        ...
9909  0.400000
9910  0.383333
9911  0.400000
9912  0.400000
9913  0.700000

[9914 rows x 1 columns]

In [9]:
checkpoint5_fare_amt = checkpoint5.join(labels)
checkpoint5_traffic = checkpoint5_fare_amt.join(traffic_density_df)
checkpoint5_traffic

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,time,day,weekend,holiday,peak_hour,hotspot,dist,fare_amount,0
0,-73.844311,40.721319,-73.841610,40.712278,1,17:26:21,0,0,0,1,0,1.030764,4.5,0.383333
1,-74.016048,40.711303,-73.979268,40.782004,1,16:52:16,1,0,0,1,0,8.450134,16.9,0.383333
2,-73.982738,40.761270,-73.991242,40.750562,2,00:35:00,3,0,0,0,1,1.389525,5.7,0.383333
3,-73.987130,40.733143,-73.991567,40.758092,1,04:30:42,5,1,0,0,1,2.799270,7.7,0.700000
4,-73.968095,40.768008,-73.956655,40.783762,1,07:51:00,1,0,0,1,0,1.999157,5.3,0.383333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54125939,-74.005272,40.740027,-73.963280,40.762555,1,03:28:00,5,1,0,0,0,4.334397,14.0,0.400000
54125940,-73.957784,40.765530,-73.951640,40.773959,1,20:46:20,1,0,0,0,0,1.070590,4.2,0.083333
54125941,-73.970505,40.752325,-73.960537,40.797342,1,22:04:24,5,1,0,0,0,5.075548,14.1,0.400000
54125942,-73.980901,40.764629,-73.870605,40.773963,1,05:57:51,2,0,0,0,0,9.346157,28.9,0.083333
54125943,-73.969722,40.797668,-73.970885,40.783313,1,11:33:00,4,1,0,0,0,1.599203,7.5,0.400000

In [14]:
kaggle_test_traffic = kaggle_test.join(traffic_density_kt_df)
kaggle_test_traffic

,key,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,day,weekend,holiday,peak_hour,hotspot,dist,0
0,2015-01-27 13:08:24.0000002,-73.973320,40.763805,-73.981430,40.743835,1,1,0,0,0,0,2.323260,0.083333
1,2015-01-27 13:08:24.0000003,-73.986862,40.719383,-73.998886,40.739201,1,1,0,0,0,0,2.425353,0.083333
2,2011-10-08 11:53:44.0000002,-73.982524,40.751260,-73.979654,40.746139,1,5,1,0,0,0,0.618628,0.400000
3,2012-12-01 21:12:12.0000002,-73.981160,40.767807,-73.990448,40.751635,1,5,1,0,0,0,1.961033,0.400000
4,2012-12-01 21:12:12.0000003,-73.966046,40.789775,-73.988565,40.744427,1,5,1,0,0,1,5.387301,0.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,-73.968124,40.796997,-73.955643,40.780388,6,6,1,0,0,0,2.124874,0.400000
9910,2015-01-12 17:05:51.0000001,-73.945511,40.803600,-73.960213,40.776371,6,0,0,0,1,0,3.270969,0.383333
9911,2015-04-19 20:44:15.0000001,-73.991600,40.726608,-73.789742,40.647011,6,6,1,0,0,0,19.183941,0.400000
9912,2015-01-31 01:05:19.0000005,-73.985573,40.735432,-73.939178,40.801731,6,5,1,0,0,0,8.343486,0.400000
9913,2015-01-18 14:06:23.0000006,-73.988022,40.754070,-74.000282,40.759220,6,6,1,0,0,1,1.180825,0.700000

In [10]:
#rename the traffic column
checkpoint5_traffic.rename(columns={"0":"traffic_density"}, inplace=True)
checkpoint5_traffic

,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,time,day,weekend,holiday,peak_hour,hotspot,dist,fare_amount,traffic_density
0,-73.844311,40.721319,-73.841610,40.712278,1,17:26:21,0,0,0,1,0,1.030764,4.5,0.383333
1,-74.016048,40.711303,-73.979268,40.782004,1,16:52:16,1,0,0,1,0,8.450134,16.9,0.383333
2,-73.982738,40.761270,-73.991242,40.750562,2,00:35:00,3,0,0,0,1,1.389525,5.7,0.383333
3,-73.987130,40.733143,-73.991567,40.758092,1,04:30:42,5,1,0,0,1,2.799270,7.7,0.700000
4,-73.968095,40.768008,-73.956655,40.783762,1,07:51:00,1,0,0,1,0,1.999157,5.3,0.383333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
54125939,-74.005272,40.740027,-73.963280,40.762555,1,03:28:00,5,1,0,0,0,4.334397,14.0,0.400000
54125940,-73.957784,40.765530,-73.951640,40.773959,1,20:46:20,1,0,0,0,0,1.070590,4.2,0.083333
54125941,-73.970505,40.752325,-73.960537,40.797342,1,22:04:24,5,1,0,0,0,5.075548,14.1,0.400000
54125942,-73.980901,40.764629,-73.870605,40.773963,1,05:57:51,2,0,0,0,0,9.346157,28.9,0.083333
54125943,-73.969722,40.797668,-73.970885,40.783313,1,11:33:00,4,1,0,0,0,1.599203,7.5,0.400000

In [15]:
#rename the traffic column
kaggle_test_traffic.rename(columns={"0":"traffic_density"}, inplace=True)
kaggle_test_traffic

,key,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,passenger_count,day,weekend,holiday,peak_hour,hotspot,dist,traffic_density
0,2015-01-27 13:08:24.0000002,-73.973320,40.763805,-73.981430,40.743835,1,1,0,0,0,0,2.323260,0.083333
1,2015-01-27 13:08:24.0000003,-73.986862,40.719383,-73.998886,40.739201,1,1,0,0,0,0,2.425353,0.083333
2,2011-10-08 11:53:44.0000002,-73.982524,40.751260,-73.979654,40.746139,1,5,1,0,0,0,0.618628,0.400000
3,2012-12-01 21:12:12.0000002,-73.981160,40.767807,-73.990448,40.751635,1,5,1,0,0,0,1.961033,0.400000
4,2012-12-01 21:12:12.0000003,-73.966046,40.789775,-73.988565,40.744427,1,5,1,0,0,1,5.387301,0.700000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9909,2015-05-10 12:37:51.0000002,-73.968124,40.796997,-73.955643,40.780388,6,6,1,0,0,0,2.124874,0.400000
9910,2015-01-12 17:05:51.0000001,-73.945511,40.803600,-73.960213,40.776371,6,0,0,0,1,0,3.270969,0.383333
9911,2015-04-19 20:44:15.0000001,-73.991600,40.726608,-73.789742,40.647011,6,6,1,0,0,0,19.183941,0.400000
9912,2015-01-31 01:05:19.0000005,-73.985573,40.735432,-73.939178,40.801731,6,5,1,0,0,0,8.343486,0.400000
9913,2015-01-18 14:06:23.0000006,-73.988022,40.754070,-74.000282,40.759220,6,6,1,0,0,1,1.180825,0.700000

In [11]:
checkpoint5_traffic.to_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/own_eqn/checkpoint5_traffic.csv', index=False)

In [16]:
kaggle_test_traffic.to_csv('/Users/sankeerthana/Documents/NTU/YEAR_3/CZ4041_ML/Lab/own_eqn/kaggle_test_traffic.csv', index=False)